In [2]:
import pandas as pd

# Load training data
train_df = pd.read_csv("../data/fraudTrain.csv")

# Show first 5 rows
train_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [3]:
train_df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='str')

In [4]:
# Drop useless columns
train_df = train_df.drop(columns=[
    'Unnamed: 0',     # just index
    'first', 'last',  # names (not useful)
    'street', 'city', 'state', 'zip',  # too detailed address
    'trans_num'       # transaction ID (random)
])

train_df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,46.2306,-112.1138,1939,Patent attorney,1967-01-12,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,1325376186,38.674999,-78.632459,0

In [5]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 15 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  str
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  str
 3   category               1296675 non-null  str
 4   amt                    1296675 non-null  float64
 5   gender                 1296675 non-null  str
 6   lat                    1296675 non-null  float64
 7   long                   1296675 non-null  float64
 8   city_pop               1296675 non-null  int64
 9   job                    1296675 non-null  str
 10  dob                    1296675 non-null  str
 11  unix_time              1296675 non-null  int64
 12  merch_lat              1296675 non-null  float64
 13  merch_long             1296675 non-null  float64
 14  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(4), str(6)
memory usage: 252.1 MB

In [6]:
# Convert gender to numbers
train_df['gender'] = train_df['gender'].map({'M': 0, 'F': 1})

train_df['gender'].head()

0    1
1    1
2    0
3    0
4    0
Name: gender, dtype: int64

In [7]:
# Convert category into numbers using encoding
train_df['category'] = train_df['category'].astype('category').cat.codes

train_df['category'].head()

0    8
1    4
2    0
3    2
4    9
Name: category, dtype: int8

In [8]:
# Convert job into numbers
train_df['job'] = train_df['job'].astype('category').cat.codes

train_df['job'].head()

0    370
1    428
2    307
3    328
4    116
Name: job, dtype: int16

In [9]:
train_df = train_df.drop(columns=['merchant'])

train_df.head()

,trans_date_trans_time,cc_num,category,amt,gender,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,8,4.97,1,36.0788,-81.1781,3495,370,1988-03-09,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,4,107.23,1,48.8878,-118.2105,149,428,1978-06-21,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,0,220.11,0,42.1808,-112.2620,4154,307,1962-01-19,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,2,45.00,0,46.2306,-112.1138,1939,328,1967-01-12,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,9,41.96,0,38.4207,-79.4629,99,116,1986-03-28,1325376186,38.674999,-78.632459,0

In [16]:
for col in train_df.columns:
    print(col)

cc_num
category
amt
gender
lat
long
city_pop
job
unix_time
merch_lat
merch_long
is_fraud
age
hour

In [18]:
# Reload fresh data
import pandas as pd

train_df = pd.read_csv("../data/fraudTrain.csv")

train_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [19]:
# Convert transaction time to datetime
train_df['trans_date_trans_time'] = pd.to_datetime(train_df['trans_date_trans_time'])

# Extract hour
train_df['hour'] = train_df['trans_date_trans_time'].dt.hour

# Check result
train_df[['trans_date_trans_time', 'hour']].head()

  trans_date_trans_time  hour
0   2019-01-01 00:00:18     0
1   2019-01-01 00:00:44     0
2   2019-01-01 00:00:51     0
3   2019-01-01 00:01:16     0
4   2019-01-01 00:03:06     0

In [20]:
train_df['hour'].unique()[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [21]:
train_df[['trans_date_trans_time', 'hour']].tail()

        trans_date_trans_time  hour
1296670   2020-06-21 12:12:08    12
1296671   2020-06-21 12:12:19    12
1296672   2020-06-21 12:12:32    12
1296673   2020-06-21 12:13:36    12
1296674   2020-06-21 12:13:37    12

In [22]:
# Convert dob to datetime
train_df['dob'] = pd.to_datetime(train_df['dob'])

# Create age feature
train_df['age'] = 2026 - train_df['dob'].dt.year

# Check result
train_df[['dob', 'age']].head()

         dob  age
0 1988-03-09   38
1 1978-06-21   48
2 1962-01-19   64
3 1967-01-12   59
4 1986-03-28   40

In [23]:
# Drop unnecessary columns
train_df = train_df.drop(columns=[
    'Unnamed: 0',
    'first', 'last',
    'street', 'city', 'state', 'zip',
    'trans_num',
    'trans_date_trans_time',
    'cc_num'
])

train_df.head()

,merchant,category,amt,gender,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud,hour,age
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,1325376018,36.011293,-82.048315,0,0,38
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1325376044,49.159047,-118.186462,0,0,48
2,fraud_Lind-Buckridge,entertainment,220.11,M,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,1325376051,43.150704,-112.154481,0,0,64
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,46.2306,-112.1138,1939,Patent attorney,1967-01-12,1325376076,47.034331,-112.561071,0,0,59
4,fraud_Keeling-Crist,misc_pos,41.96,M,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,1325376186,38.674999,-78.632459,0,0,40

In [24]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = train_df.drop('is_fraud', axis=1)
y = train_df['is_fraud']

# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

ModuleNotFoundError: No module named 'sklearn'

In [26]:
from sklearn.model_selection import train_test_split
print(X_train.shape, X_test.shape)

NameError: name 'X_train' is not defined

In [27]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = train_df.drop('is_fraud', axis=1)
y = train_df['is_fraud']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Print shapes
print(X_train.shape, X_test.shape)

(1037340, 14) (259335, 14)

In [28]:
from sklearn.linear_model import LogisticRegression

# Create model
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'fraud_Kris-Kertzmann'

In [29]:
train_df.select_dtypes(include='object').columns

C:\Users\intern_4\AppData\Local\Temp\ipykernel_31492\2620362173.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  train_df.select_dtypes(include='object').columns

Index(['merchant', 'category', 'gender', 'job'], dtype='str')

In [30]:
train_df = train_df.drop(columns=train_df.select_dtypes(include='object').columns)

train_df.head()

C:\Users\intern_4\AppData\Local\Temp\ipykernel_31492\1387711207.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  train_df = train_df.drop(columns=train_df.select_dtypes(include='object').columns)

,amt,lat,long,city_pop,dob,unix_time,merch_lat,merch_long,is_fraud,hour,age
0,4.97,36.0788,-81.1781,3495,1988-03-09,1325376018,36.011293,-82.048315,0,0,38
1,107.23,48.8878,-118.2105,149,1978-06-21,1325376044,49.159047,-118.186462,0,0,48
2,220.11,42.1808,-112.2620,4154,1962-01-19,1325376051,43.150704,-112.154481,0,0,64
3,45.00,46.2306,-112.1138,1939,1967-01-12,1325376076,47.034331,-112.561071,0,0,59
4,41.96,38.4207,-79.4629,99,1986-03-28,1325376186,38.674999,-78.632459,0,0,40

In [31]:
from sklearn.model_selection import train_test_split

X = train_df.drop('is_fraud', axis=1)
y = train_df['is_fraud']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [32]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Float64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int32DType'>, <class 'numpy.dtypes.Int32DType'>)

In [33]:
train_df = train_df.drop(columns=['trans_date_trans_time'])

KeyError: "['trans_date_trans_time'] not found in axis"

In [34]:
# Drop all datetime-like and unwanted columns
train_df = train_df.drop(columns=[
    'trans_date_trans_time',  # if exists (safe even if not)
    'unix_time'
], errors='ignore')

train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   amt         1296675 non-null  float64
 1   lat         1296675 non-null  float64
 2   long        1296675 non-null  float64
 3   city_pop    1296675 non-null  int64
 4   dob         1296675 non-null  datetime64[us]
 5   merch_lat   1296675 non-null  float64
 6   merch_long  1296675 non-null  float64
 7   is_fraud    1296675 non-null  int64
 8   hour        1296675 non-null  int32
 9   age         1296675 non-null  int32
dtypes: datetime64[us](1), float64(5), int32(2), int64(2)
memory usage: 89.0 MB

In [35]:
train_df = train_df.drop(columns=['dob'])

In [36]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 9 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   amt         1296675 non-null  float64
 1   lat         1296675 non-null  float64
 2   long        1296675 non-null  float64
 3   city_pop    1296675 non-null  int64
 4   merch_lat   1296675 non-null  float64
 5   merch_long  1296675 non-null  float64
 6   is_fraud    1296675 non-null  int64
 7   hour        1296675 non-null  int32
 8   age         1296675 non-null  int32
dtypes: float64(5), int32(2), int64(2)
memory usage: 79.1 MB

In [37]:
from sklearn.model_selection import train_test_split

X = train_df.drop('is_fraud', axis=1)
y = train_df['is_fraud']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [38]:
# Make predictions
y_pred = model.predict(X_test)

y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
y_test.value_counts()

is_fraud
0    257815
1      1520
Name: count, dtype: int64

In [40]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[257671    144]
 [  1520      0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00    257815
           1       0.00      0.00      0.00      1520

    accuracy                           0.99    259335
   macro avg       0.50      0.50      0.50    259335
weighted avg       0.99      0.99      0.99    259335

In [43]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

In [44]:
y_train_res.value_counts()

is_fraud
0    1031354
1    1031354
Name: count, dtype: int64

In [42]:
pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\Users\intern_4\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (2.4.3)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\Users\intern_4\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\Users\intern_4\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\Users\intern_4\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\Users\intern_4\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored

In [45]:
is_fraud
0    1031354
1    1031354
Name: count, dtype: int64

SyntaxError: invalid syntax (4217316504.py, line 2)

In [46]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_res, y_train_res)

LogisticRegression(max_iter=1000)

In [47]:
y_pred = model.predict(X_test)

In [48]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[244819  12996]
 [   358   1162]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97    257815
           1       0.08      0.76      0.15      1520

    accuracy                           0.95    259335
   macro avg       0.54      0.86      0.56    259335
weighted avg       0.99      0.95      0.97    259335